/**
 * DevAgent — post-pipeline development chat agent.
 * Takes user instructions and generates file changes (create/modify/delete)
 * for the existing GitHub repo+branch.
 */
import type { FileChange, DevSessionContext, FileTreeNode } from '../../../types/dev-session.js';

export interface DevAIDeps {
  generateText(systemPrompt: string, userPrompt: string): Promise<string>;
}

export interface DevAgentInput {
  userMessage: string;
  context: DevSessionContext;
}

export interface DevAgentOutput {
  response: string;
  fileChanges: FileChange[];
}

export class DevAgent {
  private aiDeps: DevAIDeps;

  constructor(aiDeps: DevAIDeps) {
    this.aiDeps = aiDeps;
  }

  async run(input: DevAgentInput): Promise<DevAgentOutput> {
    const systemPrompt = this.buildSystemPrompt(input.context);
    const userPrompt = this.buildUserPrompt(input);

    console.log(`[DevAgent] Prompt sizes: system=${systemPrompt.length} chars, user=${userPrompt.length} chars, est tokens=${Math.ceil((systemPrompt.length + userPrompt.length) / 4)}`);

    const rawResponse = await this.aiDeps.generateText(systemPrompt, userPrompt);

    return this.parseResponse(rawResponse);
  }

  private buildSystemPrompt(context: DevSessionContext): string {
    let fileTreeStr = this.formatFileTree(context.fileTree);
    // Aggressively truncate to stay under 30k input token API limit
    if (fileTreeStr.length > 2000) {
      fileTreeStr = fileTreeStr.slice(0, 2000) + '\n... (truncated)';
    }
    const specStr = context.spec ? JSON.stringify(context.spec, null, 2).slice(0, 1500) : 'N/A';

    return `You are AKIS DevAgent. You help the user develop their existing project further.

## PROJECT CONTEXT

### Previous Spec (generated by Scribe)
${specStr}

### Current File Structure (GitHub: ${context.repoOwner}/${context.repoName}, branch: ${context.branch})
${fileTreeStr}

## TASK

The user will send you feature requests, bug fixes, refactoring tasks, or any development instruction. You must:

1. Explain what you will do and why
2. Specify which files to create/modify/delete
3. Generate the full code for each file

## OUTPUT FORMAT

1. First, write a plain text explanation (what you're doing and why)
2. Then specify file changes in this XML format:

<file_changes>
<change action="create" path="src/pages/Login.tsx">
Full file content here...
</change>
<change action="modify" path="src/App.tsx">
Full NEW file content here (entire file, not just the diff)...
</change>
<change action="delete" path="src/old-file.ts" />
</file_changes>

## RULES

- Always provide FULL file content (not diffs, the entire file)
- Be consistent with the existing file structure (correct import paths)
- Preserve the project's tech stack (existing framework, language, style)
- Make focused, small changes — don't modify too many files at once
- Always explain what you are doing
- File paths should be from the project root (no leading /)
- If you don't know a file's current content, infer from the file structure
- Ask the user if you're unsure`;
  }

  private buildUserPrompt(input: DevAgentInput): string {
    // Build chat history for context
    const historyLines = input.context.chatHistory.map((msg) => {
      if (msg.role === 'assistant' && msg.fileChanges?.length) {
        return `Assistant: ${msg.content}\n[${msg.fileChanges.length} file change(s) applied]`;
      }
      return `${msg.role === 'user' ? 'User' : 'Assistant'}: ${msg.content}`;
    });

    if (historyLines.length > 0) {
      return `## Previous conversation:\n${historyLines.join('\n\n')}\n\n## New message:\n${input.userMessage}`;
    }

    return input.userMessage;
  }

  private parseResponse(rawResponse: string): DevAgentOutput {
    const fileChangesMatch = rawResponse.match(/<file_changes>([\s\S]*?)<\/file_changes>/);
    let fileChanges: FileChange[] = [];
    let textResponse = rawResponse;

    if (fileChangesMatch) {
      textResponse = rawResponse.replace(/<file_changes>[\s\S]*?<\/file_changes>/, '').trim();
      fileChanges = this.parseFileChanges(fileChangesMatch[1]);
    }

    return {
      response: textResponse,
      fileChanges,
    };
  }

  private parseFileChanges(xml: string): FileChange[] {
    const changes: FileChange[] = [];
    const changeRegex = /<change\s+action="(create|modify|delete)"\s+path="([^"]+)"(?:\s*\/>|>([\s\S]*?)<\/change>)/g;

    let match;
    while ((match = changeRegex.exec(xml)) !== null) {
      changes.push({
        action: match[1] as 'create' | 'modify' | 'delete',
        path: match[2],
        content: match[3]?.trim() || undefined,
      });
    }

    return changes;
  }

  private formatFileTree(tree: FileTreeNode[], indent = '', depth = 0): string {
    if (!tree || tree.length === 0) return '(empty)';

    // Limit depth to 3 levels and total lines to prevent exceeding token limits
    const MAX_DEPTH = 3;
    let result = '';
    for (const node of tree) {
      if (node.type === 'dir') {
        result += `${indent}${node.path}/\n`;
        if (node.children && depth < MAX_DEPTH) {
          result += this.formatFileTree(node.children, indent + '  ', depth + 1);
        } else if (node.children && depth >= MAX_DEPTH) {
          const childCount = node.children.length;
          result += `${indent}  ... (${childCount} items)\n`;
        }
      } else {
        result += `${indent}${node.path}\n`;
      }
    }
    return result;
  }
}
