import { useState, useEffect, useRef } from 'react';

type PreviewView = 'web' | 'mobile';

interface PreviewPanelProps {
  files: Record<string, string> | null;
  title?: string;
  loading?: boolean;
  branch?: string;
}

/** Strip leading slashes from file keys — StackBlitz expects 'src/App.tsx', not '/src/App.tsx' */
function normalizeFiles(raw: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(raw)) {
    const clean = key.startsWith('/') ? key.slice(1) : key;
    out[clean] = value;
  }

  // Inject StackBlitz startCommand into package.json if missing
  if (out['package.json']) {
    try {
      const pkg = JSON.parse(out['package.json']);
      if (!pkg.stackblitz) {
        pkg.stackblitz = {
          installDependencies: true,
          startCommand: pkg.scripts?.dev ? 'npm run dev'
            : pkg.scripts?.start ? 'npm start'
            : 'npm run dev',
        };
        out['package.json'] = JSON.stringify(pkg, null, 2);
      }
    } catch { /* preserve original */ }
  }

  return out;
}

function findMainFile(files: Record<string, string>): string {
  const priorities = [
    'src/App.tsx', 'src/App.jsx', 'src/App.js',
    'src/index.tsx', 'src/index.jsx', 'src/index.js',
    'src/main.tsx', 'src/main.jsx', 'src/main.js',
    'index.html', 'App.jsx', 'App.js',
  ];
  for (const p of priorities) {
    if (files[p]) return p;
  }
  return Object.keys(files)[0] || 'index.html';
}

function detectTemplate(files: Record<string, string>): 'node' | 'html' {
  if (files['package.json']) return 'node';
  if (files['index.html']) return 'html';
  return 'node';
}

export function PreviewPanel({ files, title, loading: externalLoading, branch }: PreviewPanelProps) {
  const [view, setView] = useState<PreviewView>('web');
  const [status, setStatus] = useState<'idle' | 'loading' | 'ready' | 'error'>('idle');
  const [error, setError] = useState<string | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const [retryKey, setRetryKey] = useState(0);

  useEffect(() => {
    if (!files || Object.keys(files).length === 0 || !containerRef.current) return;

    const container = containerRef.current;
    let cancelled = false;

    async function loadPreview() {
      try {
        setStatus('loading');
        setError(null);

        // Clear existing iframe
        container.innerHTML = '';

        // Dynamic import to reduce bundle size
        const sdk = await import('@stackblitz/sdk');

        if (cancelled) return;

        const normalized = normalizeFiles(files!);
        const template = detectTemplate(normalized);
        const mainFile = findMainFile(normalized);

        await sdk.default.embedProject(
          container,
          {
            title: title || 'AKIS Preview',
            description: 'Generated by AKIS Pipeline',
            template,
            files: normalized,
          },
          {
            openFile: mainFile,
            view: 'preview',
            hideNavigation: true,
            height: '100%',
          },
        );

        if (!cancelled) setStatus('ready');
      } catch (err) {
        if (!cancelled) {
          console.error('Preview error:', err);
          setError(err instanceof Error ? err.message : 'Önizleme yüklenemedi');
          setStatus('error');
        }
      }
    }

    loadPreview();

    return () => {
      cancelled = true;
      container.innerHTML = '';
    };
  }, [files, title, retryKey]);

  const isLoading = externalLoading || status === 'loading';

  return (
    <div className="flex h-full flex-col overflow-hidden bg-ak-surface">
      {/* Header */}
      <div className="flex flex-shrink-0 items-center gap-2 border-b border-ak-border px-3 py-2">
        <span className="text-xs">🖥</span>
        <span className="text-sm font-semibold text-ak-text-primary">Önizleme</span>
        <div className="flex-1" />

        {/* View toggle */}
        <div className="flex rounded-md border border-ak-border bg-ak-surface-2 p-0.5">
          <button
            onClick={() => setView('web')}
            className={`rounded px-2 py-0.5 text-[10px] font-medium transition-colors ${
              view === 'web'
                ? 'bg-ak-primary/20 text-ak-primary'
                : 'text-ak-text-tertiary hover:text-ak-text-secondary'
            }`}
          >
            Web
          </button>
          <button
            onClick={() => setView('mobile')}
            className={`rounded px-2 py-0.5 text-[10px] font-medium transition-colors ${
              view === 'mobile'
                ? 'bg-ak-primary/20 text-ak-primary'
                : 'text-ak-text-tertiary hover:text-ak-text-secondary'
            }`}
          >
            📱
          </button>
        </div>
      </div>

      {/* Preview body */}
      <div className="relative flex flex-1 items-center justify-center overflow-hidden bg-ak-bg p-2">
        {isLoading && (
          <div className="absolute inset-0 z-10 flex flex-col items-center justify-center bg-ak-surface gap-3">
            <div className="relative h-8 w-8">
              <div className="h-8 w-8 animate-spin rounded-full border-2 border-ak-primary border-t-transparent" />
              <span className="absolute inset-0 flex items-center justify-center text-xs">⚡</span>
            </div>
            <p className="text-sm font-medium text-ak-text-secondary">
              {externalLoading ? 'Dosyalar getiriliyor...' : 'Önizleme başlatılıyor...'}
            </p>
            <p className="text-[10px] text-ak-text-tertiary">
              {externalLoading ? 'Proto dosyaları çekiliyor' : 'StackBlitz WebContainer yükleniyor'}
            </p>
            <div className="mt-1 h-1 w-32 overflow-hidden rounded-full bg-ak-border">
              <div
                className="h-full rounded-full bg-ak-primary/50 transition-all duration-1000"
                style={{ width: externalLoading ? '30%' : '60%', animation: 'pulse 2s ease-in-out infinite' }}
              />
            </div>
          </div>
        )}

        {error && !isLoading && (
          <div className="absolute inset-0 z-10 flex flex-col items-center justify-center bg-ak-surface gap-3 px-6 text-center">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-red-500/10">
              <svg className="h-5 w-5 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
              </svg>
            </div>
            <p className="text-sm font-medium text-red-400">Önizleme yüklenemedi</p>
            <p className="text-xs text-ak-text-tertiary">{error}</p>
            <button
              onClick={() => setRetryKey(k => k + 1)}
              className="mt-2 rounded-lg bg-ak-primary/10 px-4 py-2 text-xs font-medium text-ak-primary transition-colors hover:bg-ak-primary/20"
            >
              Tekrar Dene
            </button>
          </div>
        )}

        {!files && !externalLoading && (
          <div className="absolute inset-0 z-10 flex flex-col items-center justify-center bg-ak-surface gap-2 text-center">
            <p className="text-xs text-ak-text-tertiary">Henüz dosya yok. Proto tamamlandığında preview burada görünecek.</p>
          </div>
        )}

        {/* Mobile/Web wrapper — CSS-only toggle, no SDK re-call */}
        <div
          className="overflow-hidden transition-all duration-300"
          style={
            view === 'mobile'
              ? {
                  width: 390,
                  height: 844,
                  maxHeight: '100%',
                  border: '8px solid var(--ak-border)',
                  borderRadius: 32,
                  margin: '16px auto',
                  boxShadow: '0 8px 32px rgba(0,0,0,0.15)',
                }
              : { width: '100%', height: '100%' }
          }
        >
          <div ref={containerRef} className="h-full w-full" />
        </div>
      </div>

      {/* Footer */}
      {branch && (
        <div className="flex items-center justify-between border-t border-ak-border px-3 py-1.5">
          <span className="font-mono text-[10px] text-ak-text-tertiary">
            ⑂ {branch}
          </span>
          <span className="text-[10px] text-ak-text-tertiary">
            Powered by StackBlitz SDK
          </span>
        </div>
      )}
    </div>
  );
}
