/**
 * RAG (Retrieval-Augmented Generation) Interfaces
 * 
 * Minimal, pluggable interfaces for vector storage and embedding generation.
 * Designed for local-first development with Qdrant, but provider-agnostic.
 * 
 * Phase 2 MVP: Interfaces + basic Qdrant implementation
 * Future: Advanced chunking, hybrid search, reranking
 */

// =============================================================================
// Core Types
// =============================================================================

/**
 * Document to be stored in vector database
 */
export interface RagDocument {
  /** Unique document identifier */
  id: string;
  /** Document text content */
  content: string;
  /** Document embedding vector (generated by EmbeddingProvider) */
  embedding: number[];
  /** Arbitrary metadata (source, timestamp, repo, etc.) */
  metadata: Record<string, unknown>;
}

/**
 * Query result from vector search
 */
export interface RagSearchResult {
  /** Document ID */
  id: string;
  /** Original document content */
  content: string;
  /** Similarity score (0-1, higher is better) */
  score: number;
  /** Document metadata */
  metadata: Record<string, unknown>;
}

/**
 * Namespace/collection for organizing documents
 * Examples: "repo_docs", "tickets", "code_snippets"
 */
export type RagNamespace = string;

// =============================================================================
// Vector Store Interface
// =============================================================================

/**
 * RagStore - Vector database abstraction
 * 
 * Implementation: QdrantRagStore (Phase 2)
 * Future: Pinecone, Weaviate, etc.
 */
export interface RagStore {
  /**
   * Upsert documents into a namespace (insert or update)
   * 
   * @param namespace - Collection/index name (e.g., "repo_docs")
   * @param documents - Documents with pre-computed embeddings
   * @throws RagStoreError if operation fails
   */
  upsert(namespace: RagNamespace, documents: RagDocument[]): Promise<void>;

  /**
   * Query for similar documents using embedding vector
   * 
   * @param namespace - Collection/index name
   * @param queryEmbedding - Query vector (from EmbeddingProvider)
   * @param topK - Number of results to return
   * @returns Sorted results (highest score first)
   * @throws RagStoreError if operation fails
   */
  query(
    namespace: RagNamespace,
    queryEmbedding: number[],
    topK: number
  ): Promise<RagSearchResult[]>;

  /**
   * Delete documents by IDs
   * 
   * @param namespace - Collection/index name
   * @param ids - Document IDs to delete
   * @throws RagStoreError if operation fails
   */
  delete(namespace: RagNamespace, ids: string[]): Promise<void>;

  /**
   * Check if namespace exists
   * 
   * @param namespace - Collection/index name
   * @returns true if exists, false otherwise
   */
  namespaceExists(namespace: RagNamespace): Promise<boolean>;

  /**
   * Create namespace with specified embedding dimension
   * 
   * @param namespace - Collection/index name
   * @param dimension - Embedding vector dimension (e.g., 384 for all-MiniLM-L6-v2)
   * @throws RagStoreError if creation fails
   */
  createNamespace(namespace: RagNamespace, dimension: number): Promise<void>;

  /**
   * Get store health status (for monitoring/debugging)
   */
  healthCheck(): Promise<{ healthy: boolean; message?: string }>;
}

// =============================================================================
// Embedding Provider Interface
// =============================================================================

/**
 * EmbeddingProvider - Text-to-vector transformation
 * 
 * Implementation: LocalEmbeddingProvider (Phase 2 MVP - CPU-based)
 * Future: OpenAI embeddings, Cohere, custom fine-tuned models
 */
export interface EmbeddingProvider {
  /**
   * Generate embeddings for text inputs
   * 
   * @param texts - Input texts (batched for efficiency)
   * @returns Embedding vectors (same order as inputs)
   * @throws EmbeddingError if generation fails
   */
  embed(texts: string[]): Promise<number[][]>;

  /**
   * Get embedding dimension (e.g., 384, 768, 1536)
   * Must be consistent for all embeddings in a namespace
   */
  getDimension(): number;

  /**
   * Get model identifier (for debugging/logging)
   */
  getModelName(): string;
}

// =============================================================================
// Error Types
// =============================================================================

export class RagStoreError extends Error {
  constructor(
    public code: string,
    message: string,
    public details?: unknown
  ) {
    super(message);
    this.name = 'RagStoreError';
  }
}

export class EmbeddingError extends Error {
  constructor(
    public code: string,
    message: string,
    public details?: unknown
  ) {
    super(message);
    this.name = 'EmbeddingError';
  }
}

