import { AgentPlaybook } from './types.js';

export const protoPlaybook: AgentPlaybook = {
  agentType: 'proto',
  displayName: 'Proto Agent',
  description: 'Generates complete, runnable MVP project scaffolds from requirements with specialized AI-powered code generation and structured file output.',
  phases: [
    {
      id: 'thinking',
      label: 'Thinking',
      description: 'Analyzing requirements, detecting stack, and planning architecture',
      icon: '🧠',
      estimatedDurationMs: 5000,
    },
    {
      id: 'discovery',
      label: 'Discovery',
      description: 'Planning project structure, file layout, and dependency graph',
      icon: '🔍',
      estimatedDurationMs: 8000,
    },
    {
      id: 'creating',
      label: 'Creating',
      description: 'AI-generating complete project files: source code, configs, tests, README',
      icon: '✍️',
      estimatedDurationMs: 35000,
    },
    {
      id: 'reviewing',
      label: 'Reviewing',
      description: 'AI reflection on scaffold completeness and quality',
      icon: '🔎',
      estimatedDurationMs: 15000,
    },
    {
      id: 'publishing',
      label: 'Publishing',
      description: 'Committing scaffold files and creating pull request',
      icon: '🚀',
      estimatedDurationMs: 10000,
    },
    {
      id: 'done',
      label: 'Done',
      description: 'MVP scaffold generation complete',
      icon: '✅',
    },
  ],
  requiredFields: [
    {
      name: 'requirements',
      type: 'string',
      label: 'Requirements',
      required: true,
      placeholder: 'Describe what you want to build...',
    },
    {
      name: 'stack',
      type: 'string',
      label: 'Tech Stack',
      required: false,
      placeholder: 'e.g. React + Node.js + PostgreSQL',
    },
    {
      name: 'owner',
      type: 'string',
      label: 'Repository Owner',
      required: false,
      placeholder: 'e.g. octocat',
    },
    {
      name: 'repo',
      type: 'string',
      label: 'Repository Name',
      required: false,
      placeholder: 'e.g. my-project',
    },
    {
      name: 'baseBranch',
      type: 'string',
      label: 'Base Branch',
      required: false,
      placeholder: 'e.g. main',
      defaultValue: 'main',
    },
    {
      name: 'dryRun',
      type: 'boolean',
      label: 'Dry Run',
      required: false,
      defaultValue: false,
    },
  ],
  capabilities: [
    'Specialized AI-powered scaffold generation (PROTO_GENERATE_SYSTEM_PROMPT)',
    'Structured multi-file output with intelligent parsing',
    'Stack-aware code generation (auto-detect or user-specified)',
    'Complete project: README, configs, source, tests, .gitignore',
    'GitHub integration (branch, commit, PR)',
    'Granular progress logging via TraceRecorder',
    'AI reflection step for quality assurance',
    'Requirements or goal-based input',
  ],
  outputArtifacts: [
    'project-scaffold',
    'pull-request',
    'readme',
    'test-stubs',
  ],
};
