import { AgentPlaybook } from './types.js';

export const tracePlaybook: AgentPlaybook = {
  agentType: 'trace',
  displayName: 'Trace Agent',
  description: 'Generates comprehensive test plans, coverage matrices, executable Playwright tests, and risk assessments by deeply analyzing specifications and source code with multi-pass AI generation.',
  phases: [
    {
      id: 'thinking',
      label: 'Thinking',
      description: 'Analyzing test specification, classifying priorities (P0-P3), detecting test layers',
      icon: '🧠',
      estimatedDurationMs: 5000,
    },
    {
      id: 'discovery',
      label: 'Discovery',
      description: 'Deep recursive repo scan: routes, models, services, existing tests, tech stack detection',
      icon: '🔍',
      estimatedDurationMs: 25000,
    },
    {
      id: 'creating',
      label: 'Creating',
      description: 'Multi-pass AI generation: test strategy → executable Playwright code → coverage analysis',
      icon: '✍️',
      estimatedDurationMs: 60000,
    },
    {
      id: 'reviewing',
      label: 'Reviewing',
      description: 'Evaluating test coverage, priority distribution, flakiness risk, and gap analysis',
      icon: '🔬',
      estimatedDurationMs: 15000,
    },
    {
      id: 'publishing',
      label: 'Publishing',
      description: 'Committing test plan, Playwright tests, coverage matrix, risk assessment, and PR creation',
      icon: '🚀',
      estimatedDurationMs: 15000,
    },
    {
      id: 'done',
      label: 'Done',
      description: 'Test plan generation complete',
      icon: '✅',
    },
  ],
  requiredFields: [
    {
      name: 'spec',
      type: 'string',
      label: 'Test Specification',
      required: true,
      placeholder: 'Paste your test specification, user stories, or Gherkin scenarios here...',
    },
    {
      name: 'owner',
      type: 'string',
      label: 'Repository Owner',
      required: false,
      placeholder: 'e.g. octocat',
    },
    {
      name: 'repo',
      type: 'string',
      label: 'Repository Name',
      required: false,
      placeholder: 'e.g. my-project',
    },
    {
      name: 'baseBranch',
      type: 'string',
      label: 'Base Branch',
      required: false,
      placeholder: 'e.g. main',
      defaultValue: 'main',
    },
    {
      name: 'dryRun',
      type: 'boolean',
      label: 'Dry Run',
      required: false,
      defaultValue: false,
    },
  ],
  capabilities: [
    'Deep recursive repository scanning (routes, models, services, tech stack)',
    'Multi-pass AI generation (strategy → code → coverage analysis)',
    'Gherkin scenario parsing (multi-scenario, Scenario Outline)',
    'Automatic priority classification (P0-P3) based on content analysis',
    'Multi-layer test detection (unit / integration / e2e)',
    'Flakiness risk assessment (low / medium / high)',
    'Executable Playwright test code with real selectors and assertions',
    'Coverage matrix with feature-to-test mapping',
    'Existing test detection and gap analysis',
    'GitHub integration (branch, commit, PR)',
    'Configurable test depth (smoke/standard/deep)',
    'Token-budgeted AI calls with layer-aware allocation',
    'Risk assessment report with recommendations',
  ],
  outputArtifacts: [
    'test-plan',
    'coverage-matrix',
    'playwright-tests',
    'risk-assessment',
  ],
};
